import "./globals.css";
import "./index.css";
import "../styles/custom.css"
import 'katex/dist/katex.min.css'
import Header from "@/components/header";
import Footer from "@/components/footer";
import Body from "@/components/body";
import { ThemeProvider } from 'next-themes'
// import { useThemeConfig } from "@/contexts/theme";

export const metadata = {
  title: "GENEA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const themeConfig = useThemeConfig()

  return (
    // <html lang="en">
    <html lang="en" className="js-focus-visible light" suppressHydrationWarning={true} dir="ltr" style={{ colorScheme: "light" }} >
      <body className="nextra-banner-hidden">
        <div dir="ltr">
          <Header />
          <Body>
            <ThemeProvider>
            {children}
            </ThemeProvider>
          </Body>
          <Footer />
        </div>
      </body>
    </html>
  );
}
