import "./globals.css";
import 'katex/dist/katex.min.css'
import Header from "@/components/header";
import Footer from "@/components/footer";
import Body from "@/components/body";

export const metadata = {
  title: "GENEA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Header />
        <Body>
          {children}
        </Body>
        <Footer />
      </body>
    </html>
  );
}
